name: TEMBA-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - HTML
  - IPython
  - ipywidgets
  - plotly
  - cufflinks
